# Generated by Django 5.1.1 on 2024-09-25 02:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='tareas/')),
                ('tipo_archivo', models.CharField(max_length=50)),
                ('cantidad_descargas', models.IntegerField(default=0)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='tasks.task')),
            ],
        ),
    ]
