# Generated by Django 5.1.1 on 2024-09-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre_comercial', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=255, unique=True)),
            ],
        ),
    ]
